### PR TITLE
Safe creation of AudioBuffer in the host

### PR DESCRIPTION
**Pull request by askeksa**
Creation of an AudioBuffer in a host is currently unsound, since the method to do so takes raw pointers and thus can't guarantee safety.

This PR is a suggestion for an API change making AudioBuffer creation in a host completely safe and sound.

The AudioBuffer needs two internal raw pointer arrays pointing to the actual input and output buffers. The lengths of these arrays correspond to the number of inputs and outputs, respectively. To keep the creation of the AudioBuffer allocation free, these buffers must be allocated up front. This is the job of the HostBuffer.

Whenever an AudioBuffer is needed, the HostBuffer is bound to the actual float arrays, and the AudioBuffer borrows the HostBuffer to ensure exclusive access to the HostBuffer arrays.

Example code is provided in the HostBuffer documentation.

### CODE REVIEW

**Comment by Boscop** [comment]
Thanks!

Btw, if you want to process a chain of plugins on a track in a double buffered / ping pong way (by using the output buffer from the previous plugin as the input to the next), you'd create two `HostBuffer`s that bind to the same buffers, but the 2nd `HostBuffer` binds to the buffers by switching the input and output buffers, right?

Like this:
```rust
let mut host_buffer_1: HostBuffer<f32> = HostBuffer::new(2, 2);
let mut host_buffer_2: HostBuffer<f32> = HostBuffer::new(2, 2);
let a_buf_left = vec![1.0; LENGTH];
let a_buf_right = vec![1.0; LENGTH];
let mut b_buf_left = vec![0.0; LENGTH];
let mut b_buf_right = vec![0.0; LENGTH];

{
	let mut (audio_buffer_1, audio_buffer_2) = {
		let mut a_bufs = [&mut a_buf_left, &mut a_buf_right];
		let mut b_bufs = [&mut b_buf_left, &mut b_buf_right];
		(
			host_buffer_1.bind(&a_bufs, &mut b_bufs),
			host_buffer_2.bind(&b_bufs, &mut a_bufs)
		)
	};
	// process first plugin in chain
	for (input, output) in audio_buffer_1.zip() {
		for (i, o) in input.iter().zip(output) {
			*o = *i * 2.0;
		}
	}
	// process second plugin in chain
	for (input, output) in audio_buffer_2.zip() {
		for (i, o) in input.iter().zip(output) {
			*o = *i + 1.0;
		}
	}

	assert_eq!(a_buf_left, vec![3.0; LENGTH]);
	assert_eq!(a_buf_right, vec![3.0; LENGTH]);
}
```

If that's the intended way to do it, we should probably also add this as a `#[test]`..
For this (common?) use case it would also be useful for `HostBuffer` to have a `bind_reverse` method that works like `bind` but switches the inputs and outputs. So in the above example it would be enough to create one `HostBuffer` and call `bind` and `bind_reverse` to create the `AudioBuffer`s for the two processing directions.

---

Maybe it would also make sense for `HostBuffer` to actually own the vecs, and just borrow them out, so that we can guarantee that the Vec's it's pointing to don't get dropped before the `HostBuffer`.

---

Btw, this was the `HostBuffer` I was using in my test host before (it works but the lifetimes aren't sound).
It also stores which processing direction is the current one (`cur_input_buf_i`) so I just call `buf.process_next_in_chain()` for each plugin in the chain and at the end of the chain I just call `buf.chain_output(..)` to get the buffers that were the output buffers for the last `plugin.process()`.
```rust
pub struct HostBuffer<'a> {
	buf_len: usize,
	channel_count: usize,
	buf_ptrs: [Vec<*mut f64>; 2],
	cur_input_buf_i: usize,
	_phantom: PhantomData<&'a mut [f64]>,
}

impl<'a> HostBuffer<'a> {
	pub fn new(buf_len: usize, channel_count: usize) -> Self {
		let buf_ptrs = [vec![null_mut(); channel_count], vec![null_mut(); channel_count]];
		Self { buf_len, channel_count, buf_ptrs, cur_input_buf_i: 0, _phantom: PhantomData }
	}
	pub fn start_chain(&mut self, input_bufs: &mut [Vec<f64>], output_bufs: &mut [Vec<f64>]) {
		debug_assert_eq!( input_bufs.len(), self.buf_ptrs[0].len());
		debug_assert_eq!( input_bufs.len(), self.buf_ptrs[1].len());
		debug_assert_eq!(output_bufs.len(), self.buf_ptrs[0].len());
		debug_assert_eq!(output_bufs.len(), self.buf_ptrs[1].len());
		let (b0, b1) = self.buf_ptrs.split_at_mut(1);
		let (input_buf_ptrs, output_buf_ptrs) = (b0[0].as_mut_slice(), b1[0].as_mut_slice());
		for (slice, ptr) in input_bufs.iter_mut().zip(input_buf_ptrs) {
			*ptr = slice.as_mut_ptr();
		}
		for (slice, ptr) in output_bufs.iter_mut().zip(output_buf_ptrs) {
			*ptr = slice.as_mut_ptr();
		}
		self.cur_input_buf_i = 0;
	}
	pub fn process_next_in_chain(&mut self, plugin: &mut PluginInstance) {
		let  input_buf_ptrs = unsafe { mem::transmute(self.buf_ptrs[self.cur_input_buf_i].as_slice()) };
		let output_buf_ptrs = &mut self.buf_ptrs[1-self.cur_input_buf_i];
		let mut audio_buf = AudioBuffer::new(input_buf_ptrs, output_buf_ptrs, self.buf_len);
		plugin.process_f64(&mut audio_buf);
		self.cur_input_buf_i ^= 1;
	}
	pub fn chain_output<'b: 'a>(&self, input_bufs: &'b mut [Vec<f64>], output_bufs: &'b mut [Vec<f64>]) -> &'b mut [Vec<f64>] {
		if self.cur_input_buf_i == 0 { input_bufs } else { output_bufs }
	}
}

fn main() {
	let host = Arc::new(Mutex::new(MyHost { sample_rate: 44100. }));
	let lp = &mut MyHost::load_vst(host.clone(), r"D:\VstPlugins\GVST\GLow.dll");
	let hp = &mut MyHost::load_vst(host.clone(), r"D:\VstPlugins\GVST\GHi.dll");
	lp.set_parameter(GVST_CUTOFF_PARAM_I, gvst_hz_to_param_norm(2000.));
	hp.set_parameter(GVST_CUTOFF_PARAM_I, gvst_hz_to_param_norm(1000.));

	let buf_len = 64;
	let channel_count = 2;
	let host = host.lock().unwrap();
	let mut wav = load_wav(r"white_noise.wav");
	wav.pad_to_multiple_of(buf_len);
	let mut  inputs = vec![vec![0.; buf_len]; channel_count];
	let mut outputs = vec![vec![0.; buf_len]; channel_count];
	let mut buf = HostBuffer::new(buf_len, channel_count);
	let mut out = wav.empty_clone();
	{
		let (outs_l, outs_r) = out.channels.split_at_mut(1);
		let (outs_l, outs_r) = (&mut outs_l[0], &mut outs_r[0]);
		for ((in_l, in_r), (out_l, out_r)) in
			wav.channels[0].chunks(buf_len).zip(wav.channels[1].chunks(buf_len))
		.zip(
			outs_l.chunks_mut(buf_len).zip(outs_r.chunks_mut(buf_len))
		) {
			for (src, dst) in in_l.iter().zip(&mut inputs[0]) { *dst = *src; }
			for (src, dst) in in_r.iter().zip(&mut inputs[1]) { *dst = *src; }
			buf.start_chain(&mut inputs, &mut outputs);
			buf.process_next_in_chain(lp);
			buf.process_next_in_chain(hp);
			let out = buf.chain_output(&mut inputs, &mut outputs);
			out_l.copy_from_slice(&out[0]);
			out_r.copy_from_slice(&out[1]);
		}
	}
	out.save("out.wav", host.sample_rate as _).unwrap();
}
```

But I'm not sure how common this use case of buffer direction switching is in real hosts, because often a plugin in the chain could have a different number of input/output channels than the one before/after. Can you comment on this? :)

**Comment by askeksa** [comment]
You would not be able to bind the buffers to both `HostBuffer`s at the same time, since the `HostBuffer` needs to borrow the output buffers exclusively.

Rather, you'd create one `HostBuffer` per plugin, corresponding to the number of inputs and outputs for that plugin. You would then bind the corresponding `HostBuffer` to the desired input and output buffers just before each process call.

I think this is the most flexible way to structure the API, as it gives the host complete freedom of how to manage its buffers.

The name "HostBuffer" is perhaps misleading. It's more like an "audio buffer binding point". Better suggestions are welcome. :)

In principle there would be nothing wrong with storing those buffer pointer arrays in the `PluginInstance` instead of having a separate struct for it. It is tied to the plugin anyway. But then the `AudioBuffer` couldn't borrow the arrays, as it would be borrowing the `PluginInstance`, and the `process` method could not be called on it while it is borrowed. Thus, the host would need to call the process method through a different interface, giving the buffers directly instead of via the `AudioBuffer` interface. It's the illusion of having the same plugin interface from the point of view of the plugin and the host which necessitates the extra mechanism for creating the `AudioBuffer`. Someone has to be responsible for allocating those arrays. :)

**Comment by piedoom** [comment]
Appveyor did the thing it does best and fail for no reason.  Consider the tests passed.

**Comment by Boscop** [comment]
Btw, are those added checks with the panics in the `process()` hot path really necessary? :)
Can't we just trust the host to give us (the plugin) the number of buffers that we asked for? 
Or did you run into situations were that wasn't the case?

It looks like this `HostBuffer` can be implemented in terms of the public API of the vst crate, wouldn't it make more sense to put it into a companion crate (specifically for creating hosts)?
Since most projects depending on the `vst` crate will be plugins rather than hosts.

Btw, I have an idea about creating a host framework crate, that allows people to easily create hosts according to their needs, kind of like the shift of web backends going from static/fixed servers like Apache to "the app contains a server, using a server framework (like nodejs or rocket)".  What I think would be interesting is a vst host framework where you can easily create and wire up a host how you need it for your specific music project. This can enable many use cases where it makes sense to have a custom host (e.g. for specific use cases of live performances, where every use case is different) or even for experimenting musically through procedural generation..
The host framework crate would contain things like the `HostBuffer`, chain/bus types (also taking care of non-stereo plugins and midi processing), so that one can load projects with it (that contain the state of the plugins, I/O wiring, etc) and call `let outputs = project.process(inputs);` as the basic functionality.
Basically the host framework would contain (in a way that is as non-opinionated as possible) all the things that any host (that's processing multiple plugins in chains) would need to impl. So that anyone writing a vst host in Rust would be able to use this host framework crate.
E.g. the `vst::Host` type would need to be instantiated for each plugin and all these host instances need to be managed and plugins need their inputs and outputs (midi and audio) to be wired into chains/tracks (or even a more flexible graph) and tracks can also send their audio to other tracks (arriving in the next frame) and be wired to hardware inputs and outputs (also both midi and audio).
The actual audio and midi backends don't need to be chosen in the host framework crate (btw, I'd use `rust-portaudio` for audio (because of ASIO support) and `midir` for midi), just the possibility to wire things up and process the whole signal chain in the most efficient way.
Also useful would be the ability to bypass/resume plugins in a chain, doing plugin-delay compensation etc. which are also desirable features for any host..

(E.g. what I'd like to have is a remote controllable host that can be operated over the network without a screen/mouse and exposing an API (like the Reaper Extension API but to the outside over the network and more consistent). It could be based on such a host framework crate because it makes sense to factor out the common host functionality, but still keep it separate from this vst crate which is the basic FFI layer.)

**Comment by askeksa** [comment]
The whole point of this change is that we don't trust the host. If we did, there wouldn't be any need for a safe API to begin with. If the host can use the API in any way that could make a well-behaved plugin crash, the API is not safe.

The functionality is indeed implemented on top of an existing API entry, but an unsafe one. Without this addition, there is no way to implement a non-trivial host (i.e. one that calls `process`) without using unsafe code. I would say that providing minimal, safe abstractions around the VST API is exactly what this crate is about (and I agree with you that anything beyond that belongs in a utility crate).

**Comment by zyvitski** [comment]
To me it would seem reasonable to either update the plugin trait to return a result or have a seperate but similar trait for the host side plugin handle

**Comment by askeksa** [comment]
As mentioned above, I sincerely think the main purpose of this crate is to provide a (minimal) safe wrapper around the unsafe VST API. Without the safeguards introduced here to keep the host from passing an incorrect number of inputs/outputs (or float arrays of mismatching lengths) to the plugin, the host can provoke undefined behavior through the API (even assuming a well-behaved client), which means it is not safe.

There are other ways to ensure valid inputs to the plugin, some of which require fewer runtime checks. The suggestion by @Boscop about having the `HostBuffer` object own the float arrays is one example. However, as far as I can see, these, more strict approaches typically impose assumptions about how a host might want to manage its buffers which do not hold in general. That is why I think the API exposed by this crate should be as minimal and flexible as possible (while remaining safe), so individual hosts can build their preferred buffer management on top of it.

**Comment by Boscop** [comment]
Then I think `panic!()` is the way to go..

**Comment by zyvitski** [comment]
@Boscop If you are good with the PR, please mark as approved.

**Pull request merged**
