### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This brings all dependencies up to date.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Once this lands, further changes can be done to improve bitflag usage as a separate pull request.

**Comment by waywardmonkeys** [comment]
The error from Travis doesn't appear to be related to my changes.

**Comment by piedoom** [comment]
Yes, the CI is a bit WIP as I'm not a pro yet. We will have to make sure docs aren't tried during PRs, I'll open an issue for that.  Consider this passing.

**Comment by piedoom** [comment]
Thanks!

**Pull request merged**
