### PR TITLE
Follow up on PR #32 to implement GetTimeInfo and others

### PR DESCRIPTION
**Pull request by klingtnet**
This PR implements @Boscop's suggestions from #32 .
I would also propose to implement a time signature type like [time_calc's TimeSig](https://docs.rs/time_calc/0.13.0/time_calc/time_sig/struct.TimeSig.html)  to make `TimeInfo` a bit more high-level.

Closes #32.

### CODE REVIEW

**Comment by klingtnet** [comment]
We should also run `rustfmt` and `clippy` in another PR on this library.

**Comment by zyvitski** [comment]
Both rustfmt and clippy have been run on the code in the past

**Comment by zyvitski** [comment]
It’s been probably about 6+ months since we’ve run either, so it makes sense that there would be new warnings and formatting

**Comment by klingtnet** [comment]
@zyvitski As said, I would do this in a separate PR to keep the diff clean.

**Comment by piedoom** [comment]
we should put something on CI that runs clippy/rustfmt automagically

**Comment by piedoom** [comment]
is this good to merge? we can run fmt on this later

**Comment by zyvitski** [comment]
Merged

**Pull request merged**
